# Welcome to my personal blog!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Contact me...
email: juan.aranda.galvis@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I'm a professional trained in academic excellence, ready to face challenges 
  and providing all my effort and my knowledge to achieve goals. My ability to 
  create personal relationships allows me to be a good team member. In the professional 
  field, I analyze in detail the environment of the requirements to offer the best 
  technology solution, which allows achieving the objectives of the business. My areas 
  of interest are:Software Engineering, software design, Software Architecture, 
  Enterprise Architecture software, agile development methodologies, Business Process, 
  Management software projects.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jparanda.github.io" # the base hostname & protocol for your site
twitter_username: jparandag
github_username:  jparanda

# Build settings
markdown: kramdown
