# Welcome to my personal blog!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Juan Pablo Aranda Galvis
email: juan.aranda.galvis@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My areas of interest are:Software Engineering, software design, Software Architecture, 
  Enterprise Architecture software, agile development methodologies, Business Process, 
  Management software projects.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jparanda.github.io" # the base hostname & protocol for your site
twitter_username: jparandag
github_username:  jparanda

# Build settings
markdown: kramdown
